name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - develop
      - release

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      
      - uses: norio-nomura/action-swiftlint@3.2.1
        name: SwiftLint
        with:
          args: --strict
  Test:
    name: Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app && /usr/bin/xcodebuild -version
    
    - name: Run Unit Tests
      run: xcodebuild test -scheme FirebaseChat -workspace FirebaseChat.xcworkspace -destination "platform=iOS Simulator,name=iPhone 12" | xcpretty && exit ${PIPESTATUS[0]}

