name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
      
      - uses: norio-nomura/action-swiftlint@3.2.1
      - name: SwiftLint
  Test:
    name: Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app && /usr/bin/xcodebuild -version
    
    - name: Run Unit Tests
      run: xcodebuild test -scheme FirebaseChat -project FirebaseChat.xcodeproj -destination "platform=iOS Simulator,name=iPhone 12, OS=14.1" | xcpretty && exit ${PIPESTATUS[0]}

