name: Continuous Integration

on:
  pull_request:
    branches: [ master develop release ]

jobs:
  Code Quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      
      - uses: norio-nomura/action-swiftlint@3.2.1
        name: SwiftLint
  Build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    
    - run: mkdir -p build/
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app && /usr/bin/xcodebuild -version
    
    - name: Build
      run: xcodebuild build-for-testing -workspace FirebaseChat.xcworkspace -scheme FirebaseChat -destination "platform=iOS Simulator,name=iPhone 12" -derivedDataPath build
    
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: build/
  Test:
    name: Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout

    - run: mkdir -p build/
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app && /usr/bin/xcodebuild -version
    
    - name: Run Unit Tests
      run: xcodebuild test-without-building -xctestrun build/Build/Products/*.xctestrun -destination "platform=iOS Simulator,name=iPhone 12" -derivedDataPath result -enableCodeCoverage yes
   
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: result/
  Code Coverage:
      name: Code Coverage
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v2
        name: Checkout
      
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app && /usr/bin/xcodebuild -version
      
      - name: Check code coverage
        run: xcrun xccov view --report --json result/Logs/Test/*.xcresult > result.json
